### ISSUE TITLE
Mention Chocolatey in README.md

### ISSUE THREAD

**Issue by cybercatgurrl** [wustho/epr#10]
I've created a chocolatey package for epr. The page for the is https://chocolatey.org/packages/epr.
My source for the package is at https://github.com/cybercatgurrl/chocolatey-pkgs/tree/master/epr.
You can mention something like you can install with Chocolatey "choco install epr" as soon as the package goes public.

Cheers!

**Comment by wustho** [comment]
Hello there, thankss for making it available in choco, but when I read it in choco package website, looks like it still uses old version of epr. I just made newer binary release: https://github.com/wustho/epr/releases/tag/v2.2.7 

Can you update epr in choco by using [`v2.2.7b`](https://github.com/wustho/epr/releases/download/v2.2.7/epr-v2.2.7b-win.zip) (_not_ `v2.2.7`) which behave like common epub reader which common people accustomed to??

**Comment by cybercatgurrl** [comment]
I can update it but just a note for the future, adding a new version in an existing tag makes it harder to process in my automatic updating scripts. I'm working on setting up an appveyor build so that it automatically updates but it would be useful not to do this in the future.

**Comment by wustho** [comment]
Thanks mate, sorry so much I know nothing about batch scripting or something...

**Comment by wustho** [comment]
Thankss @cybercatgurrl 

But I kinda lost in:

> As long as you don't add new versions to already existing tags

Can you please elaborate? What shall I do when releasing new versions so your scrit can automatically pick it up?

**Comment by cybercatgurrl** [comment]
2.2.7b is a new version and not an alternate version like md right? Will there be a 2.3.0b or 2.2.8b? If it's a separate build then I can account for that but if it was a one off thing I can't account for that. Like if 2.2.7b is a new version of the program then it would have been picked up if you made a new release.

The script will only pick it up if there is a new release. So for instance if 2.2.8 is released then it will automatically package epr-v2.2.8-win.zip and push it to chocolatey. Or should it be packaging epr-v2.2.8b-win.zip?

**Comment by wustho** [comment]
> Or should it be packaging epr-v2.2.8b-win.zip?

Is it too much bother for you if it should?

**Comment by cybercatgurrl** [comment]
Sure I can change the script to reflect that. As long as that continues to be the naming convention for releases.

**Comment by wustho** [comment]
Yess thanks so much, I will consistently update it with vX.X.Xb...

Just update the README
