### ISSUE TITLE
python3 support

### ISSUE THREAD

**Issue by dClauzel** [wustho/epr#12]
In order to install epr, I had to run the command `pip3 install git+https://github.com/wustho/epr.git`

On Debian-like systems, `pip3` comes from the package `python3-pip`.

**Comment by sleao** [comment]
I'm sorry, I don't understand what seems to be the issue, as the README states that it's written in Python3.7. Can you explain?

**Comment by dClauzel** [comment]
On (my ?) Debian, the command `pip` is associated to python2.x, and `pip3` is the command associated with python3.x. So running `pip` would fail because it would call python2.

**Comment by sleao** [comment]
That's because (I think) Debian uses python2 for some of its functions, so you have two versions of Python/pip running on your system. This isn't an issue with epr code but something specific to your system. Since the README states that the code uses Python3, I guess it's your job to make sure you use the correct package manager. We could, however, change the guide to make that clearer.

**Comment by wustho** [comment]
Yes, sorry about this... since in windows by default it's `pip` instead of `pip3` as its python3 package manager. And about 2 months ago I tried manjaro, its `pip` is already associated with `python3-pip`. So I thought newer linux releases is already comitted to python3 as its default python...

**Comment by dClauzel** [comment]
I just tested on a fresh Debian/Buster, and the behaviour is the same : `pip` is for python2 and `pip3` for python3. There is no alias pointing pip onto pip3. I suspect all the distributions derivated from Debian have the same setup.

**Comment by wustho** [comment]
Well, I'll try clarifying this up in next commit...

**Comment by czarekkwasny** [comment]
That would be most appreciated. I ran into the same issue on Fedora 30 and substituting pip for pip3 solved it for me.

**Comment by wustho** [comment]
I just did, closing this issue now...
