### ISSUE TITLE
Feature request: Support italic text

### ISSUE THREAD

**Issue by goesmin** [wustho/epr#13]
I've done a cursory check and this does not seem to be supported. Would be nice to have.

**Comment by wustho** [comment]
Hey there, I tried adding italic support, you can find its trace in probably around image-support commits... but there was an issue across platforms regarding italic's being not available in some terminal emus. Though it's probably possible to check italic support on active term, I thought it was too much works...

**Comment by wustho** [comment]
But I couldn't agree more that having italic would be nice..

**Comment by goesmin** [comment]
It might be interesting to add as an toggleable option for the time being.
Good point about italics support though. What was the issue exactly? One
would think that the emulator would handle simply displaying the text
normally.

I'll try to look into detecting italics support tomorrow but I feel it
might not be possible to do reliably.

**Comment by wustho** [comment]
We can probably use `try-except` for a start...

**Comment by pistacchio** [comment]
> Hey there, I tried adding italic support, you can find its trace in probably around image-support commits... but there was an issue across platforms regarding italic's being not available in some terminal emus. Though it's probably possible to check italic support on active term, I thought it was too much works...

Could you recover the exact commit? I'd like to give it a try and having some starting point would help. Thanks

**Comment by wustho** [comment]
Hey there @pistacchio already implemented to https://github.com/wustho/epr
