### ISSUE TITLE
pre nodes are displayed without newlines

### ISSUE THREAD

**Issue by Benaiah** [wustho/epr#16]
`pre` nodes are displayed without newlines, which makes code blocks unreadable in `epr`.

**Comment by wustho** [comment]
Well yes indeed, I havent had the time time to let it parse `pre`, since I mainly use this to read fictions instead of manuals... hoping someone else to pu requests regarding this problem...

**Comment by wustho** [comment]
Well yes indeed, I haven't had the time time to let it parse `pre`, since I mainly use this to read fictions instead of manuals... hoping someone else to pull requests regarding this problem...

**Comment by wustho** [comment]
@DeDeDeDeDestruction just fixed this with https://github.com/wustho/epr/commit/4f6b7eba7b3aa361ffab238bc6ca9818ca457840
