### ISSUE TITLE
Feature request: support *.fb2 (FictionBook) format

### ISSUE THREAD

**Issue by somospocos** [wustho/epr#22]
FictionBook is basically XML

**Comment by wustho** [comment]
Hey there, just added fictionbook format, but not in this epr, instead my own fork epy https://github.com/wustho/epy since I don't want to mess too much with this epr which is I find it stable enough.

**Comment by somospocos** [comment]
@wustho  thank you, very nice of you to let me know. I've tried it on a fb2 file and it worked. Please consider to change the project description and the README so it states explicitly that FB2 is supported too. That way it'll get indexed and will get found easier.
