### ISSUE TITLE
'unable to create directory' error

### ISSUE THREAD

**Issue by cyberalejo17** [wustho/epr#23]
When you open an image in an ePub, it shows the following error on the screen, in the end it does open the image, but it makes the screen dirty with errors.

`(nemo:4844): dconf-CRITICAL **: 16:43:18.763: unable to create directory '/run/user/0/dconf': Permiso denegado.  dconf will not work properly.`

Linux Mint 19 Cinnamon
Cinnamon 3.8.9
Xviewer 1.8.1
python 3.6

**Comment by wustho** [comment]
Hello there, I'll look up to it soon

**Comment by wustho** [comment]
Hi, can you try opening image with my epr fork, epy: https://github.com/wustho/epy and tell if it give the same error epr does?

**Comment by cyberalejo17** [comment]
Perfect! thank you. Works great. No errors

**Comment by wustho** [comment]
Glad to hear it, I'll implement it to epr
