### ISSUE TITLE
Remember last position

### ISSUE THREAD

**Issue by aeosynth** [wustho/epr#27]
Some books have glossaries, and I would like to view them, then return and continue reading. Bookmarks would work, or a jump list.

**Comment by wustho** [comment]
Hey there, actually I had been working on that when corona pandemic hit my rural region, so been busy preparing for early stage lockdown for my students... 

Now I'm in lockdown and ready to get back at it, tho it's not permanent bookmark but more like vim marking position with `ma` and jump there with `\`a`...

**Comment by wustho** [comment]
https://github.com/wustho/epr/commit/9a86b1963c8b3fe047e94eb58ca6775ad7b82499
Just added mark and jump positions. You can mark current position with `b1` (register current position to 1)  then go to glossary and mark glossary position with `b2`, then you can go back to position 1 in register with `` `1``.

**Comment by wustho** [comment]
Hey there, bookmarks feature is now available in https://github.com/wustho/epy

**Comment by aeosynth** [comment]
oh cool, thanks! closing.
