### ISSUE TITLE
Show information?

### ISSUE THREAD

**Issue by 097115** [wustho/epr#29]
Would be great if we could toggle some information display regarding the current position, like `Page 3 of 20` or `7%`

**Comment by wustho** [comment]
Hey there, we already could... It's just that I implement it in https://github.com/wustho/epy since I don't really want to mess with epr that already stable... And it's progress percentage `7%` instead of `page 3 of 20` for more minimalist approach...

**Comment by 097115** [comment]
Super, thanks!
