### ISSUE TITLE
Which font is that in the screenshot?

### ISSUE THREAD

**Issue by Vizwind** [wustho/epr#32]
This is not a real issue, but I really like to know the font name. I would like to use it for my reading. Thanks.

**Comment by wustho** [comment]
Hey there, sorry, I take that screenshot when I used windows some time ago, now I used ubuntu, so I kinda forgot about the font I used back then... But I guess it's `Overpass Mono` in bold, cmiiw.

**Comment by Vizwind** [comment]
@wustho `Overpass Mono` is not exactly the same font, `f` has an underline which is not in the ss. It's close though, thanks. Btw, nice utility, I think I will stick to it for epub reading. 

PS. The closest font I could find is IMB Plex Mono, clean and lightweight, but unfortunately there is an underline for `f`.

**Comment by wustho** [comment]
Ah that's probably the correct one. I only used these monospace fonts till now: Source Code Pro, Consoles, Overpass Mono, IBM Plex Mono.

**Comment by wustho** [comment]
Wait, I don't think it's IBM Plex Mono. The small caps `"l"` in IBM Plex Mono is hard angle while in screenshot seems smooth curve...

**Comment by wustho** [comment]
Ah I remember now... It's `Hack`! I'm pretty sure of that...

**Comment by Vizwind** [comment]
Yah it is Hack! I have it installed for a long time. What is the font in the ss of epy? https://raw.githubusercontent.com/wustho/epy/master/screenshot.png, it is even slightly better than Hack for ebook reading.

**Comment by wustho** [comment]
Pretty sure it's IBM Plex Mono, I still used it till now...

**Comment by Vizwind** [comment]
Using epy with IBM Plex Mono is fantastic! And above all it's totally free.

![image](https://user-images.githubusercontent.com/399221/86517640-11e9ea80-be5d-11ea-9c7c-d7d388c82619.png)
