### ISSUE TITLE
Feature request: Font styles

### ISSUE THREAD

**Issue by gd4c** [wustho/epr#34]
Thanks for your great app!

I was wondering if epr could support font styles (e.g. italic, bold, underline, etc)? Often, they convey meaning in ebooks.

Thanks

**Comment by wustho** [comment]
Hello there, yess totally agree, especially italic ones...

But at the time I made this, I was using python 3.3, and italic was only supported from python 3.5, so I didn't even think about styling, but now since python 3 become standard, I will probably look into it...

**Comment by wustho** [comment]
Just implemented this, but in epy instead of epr. See: https://github.com/wustho/epy/commit/9dc269dbc05d19eace32ceec27d7740ed4201c6f
