### ISSUE TITLE
feature request :: add versioning

### ISSUE THREAD

**Issue by xxKeith20xx** [wustho/epr#4]
Just realized when I posted an issue there's no version numbers. Would help for specifying issues going forward.

**Comment by wustho** [comment]
Well, let learn it a bit yeah? I heard semantic versioning, but never gave too much thought but I will from now, thankss...

I will close the issue after versioning it

**Comment by wustho** [comment]
Sorry just versioning it now, maybe too late considering before v1 I already release with config in INI format but with v1 I use JSON...
