### ISSUE TITLE
Request: Python 3.2 support for older devices

### ISSUE THREAD

**Issue by DragoonFX** [wustho/epr#42]
Will it be possible for you  provide a epr binary that uses only python 3.2?
There are some old devices that has only python 3.2 support, for example Blackberry OS 10.
We old platform users would greatly appreciate it if you would do it.
Thank you.

**Comment by wustho** [comment]
Hey there, sorry just read this. Some people say epr works on python 3.3, I'll try it on 3.2 when I have a chance.
