### ISSUE TITLE
Footnote viewer

### ISSUE THREAD

**Issue by rsaavedraxyz** [wustho/epr#45]
It would be nice to have a footnote viewer. Perhaps as a floating window popping out when you press some keybind (similar to the ToC window when you press TAB). The currently displayed text would have to be search for patterns like ^{1}.

**Comment by wustho** [comment]
Hello there, sorry just read this. I'm afraid that would be difficult for the moment. Sorry. So ^{1} isn't exactly footnote, it's more of how epr renders html tag for superscript like ¹. The difficulty in footnote implementation in epr is that there's no exact way of doing footnote in html. 

Rough example: sometimes people write footnote in html using superscript like `'¹ Some footnote explanation'`, some other times people write it like `'[1] Some footnote explanation'`. Not to mention how they write it in html form...

**Comment by wustho** [comment]
Hello there, sorry just replied... Still doing research on how actually footnote written in HTML, I found so many inconsistencies so far, like using anchor `<a>`, using fn tag `<fn>`, or other stuff... So probably this feature won't come in short time. Sorry.
