### ISSUE TITLE
Ideia

### ISSUE THREAD

**Issue by MateusRico0** [wustho/epr#48]
Hi, I don't know how to contact you, but I will delete this message here soon.
I just wanna say that I liked so much your epub reader, and I here to bring you the idea, to maybe create a writer, in the exactly same style as that epub reader.
I'm sorry to bother here
Sincerely,
Mateus

**Comment by wustho** [comment]
@MateusRico0 hey theree, no worries at all. Thanks for the idea btw. But I think there's already vim for that, with goyo plugins, vim will achieve the same look with epr.

Beside there's still so much work to prioritize for epr.

**Comment by MateusRico0** [comment]
Oh yeah, vim is good and so epr.
Again, good work and thank you
