### ISSUE TITLE
Where is dictionary integration?

### ISSUE THREAD

**Issue by newptcai** [wustho/epr#53]
The readme claims that there's integration with dictionaries. But I don't see it anywhere.

Also, is there a way to select and copy some text? That can serve as an alternative of dictionary integration.

**Comment by jneidel** [comment]
Dictionary integration is part of [`epy`](https://github.com/wustho/epy) not `epr`.

You can select and copy with your mouse, or through [`tmux`](https://github.com/tmux/tmux).

**Comment by newptcai** [comment]
This should be in the README then.

**Comment by newptcai** [comment]
Oh. It's in the README. Sorry I misread it.
