### ISSUE TITLE
can't open the pictures when more than 2 pictures are on the page

### ISSUE THREAD

**Issue by Glog78** [wustho/epr#58]
I just tried to look at the pictures on a page with 2 images. This leaded to a none reactive epr which i needed to shutdown by crtl+c ..
The console gave the following error -> 

```
Traceback (most recent call last):
  File "/usr/bin/epr", line 1272, in <module>
    main()
  File "/usr/bin/epr", line 1268, in main
    curses.wrapper(preread, file)
  File "/usr/lib/python3.10/curses/__init__.py", line 94, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/bin/epr", line 1162, in preread
    incr, width, y, pctg = reader(stdscr, epub, idx, width, y, pctg)
  File "/usr/bin/epr", line 1042, in reader
    p = pad.getch()
```

**Comment by jneidel** [comment]
Multiple images hints on one page work fine.
![screenshot_22-12-11_20:45:52](https://user-images.githubusercontent.com/25589715/206925283-e160b8b7-5503-41cf-95f7-e2cf554a9041.png)
You just have to select an image reference (with arrow keys) and press enter to open it.

**Comment by Glog78** [comment]
this can be closed. sorry for the late respond. You are right i can select it while being in a terminal only ... that didn't work in the neovim terminal but it doesn't seem to be a bug in epr.
