### ISSUE TITLE
阅读中文epub，丢失字符修改办法

### ISSUE THREAD

**Issue by kai0200** [wustho/epr#63]
行 844    `src_lines, imgs = parser.get_lines(width // 2)`   修改后，显示完整。

**Comment by shuu3** [comment]
Your solution indeed enables proper display of Chinese characters in EPUB files, without losing any characters that exceed the maximum width that can be displayed. 

However, the side effect is that, it also results in the content of English EPUB files only occupying the left half of the terminal, leaving the other half blank and wasted. 

To cater to both the old and new issues,  copy `epr.py` to a new file, modify the new file by dividing the width by 2 as your solution, and use this new file exclusively for reading EPUB files with Chinese characters (and I assume all CJK characters are the same here). Noting that replacing certain "epr" strings within the new file to match the file names is required.

It is also stated that Chinese are not supported presently in the `README.md`

**Comment by kai0200** [comment]
Thanks
