### ISSUE TITLE
Feature Request: Display Images

### ISSUE THREAD

**Issue by Chronophylos** [wustho/epr#7]
You can display images in the terminal with [w3m](http://w3m.sourceforge.net/) or by using a terminal that supports images like [kitty](https://sw.kovidgoyal.net/kitty/).
Take a look at the image [backends for neofetch](https://github.com/dylanaraps/neofetch/wiki/Image-Backends) for pretty much every option available.

**Comment by wustho** [comment]
Hello there, I just made it support images (with external viewer), please see README first. There is explanation why I probably wont make it able to display image in terminal, sorry.
