### ISSUE TITLE
Add &amp support and others

### ISSUE THREAD

**Issue by sandersantema** [wustho/epr#8]
There are some things which I found aren't displayed correctly or are not displayed at all, is there any chance for a fix? Or is this outside the scope of the project and is it only meant for simpler epub?

Some examples: 

Take for instance this epub:
https://github.com/kaunta/gnu-manuals

### **Example 1:**
- **Correct**: displayed text in iBooks
    <img width="569" alt="image" src="https://user-images.githubusercontent.com/21057514/54882103-f3720280-4e56-11e9-9c5b-ed3ca966bb15.png">

- **Incorrect**: not displayed text in epr.py
    <img width="709" alt="image" src="https://user-images.githubusercontent.com/21057514/54882117-11d7fe00-4e57-11e9-995a-2980df86232d.png">

### **Example 2:**
- **Correct**: &amp not shown in iBooks
    <img width="534" alt="image" src="https://user-images.githubusercontent.com/21057514/54882144-5fed0180-4e57-11e9-86e6-ec5154eddca3.png">

- **Incorrect**: epr.py (notice the &amp part):
    <img width="705" alt="image" src="https://user-images.githubusercontent.com/21057514/54882149-6d09f080-4e57-11e9-9041-dbb278b17047.png">

In any case thank you for the nice piece of software!

**Comment by wustho** [comment]
Hey there, thanks for let me know and fully detailed exmpl... I will look into that probably 9 hours later from now, since it's still morning on my side of the earth the time I reply this...

**Comment by wustho** [comment]
Hi, again Sander, I just made a commit regarding your problem, could you kindly check the update and letting me know if the problem still persists?

**Comment by sandersantema** [comment]
Perfect!

<img width="700" alt="image" src="https://user-images.githubusercontent.com/21057514/54931504-6a6fcf80-4f19-11e9-9bc6-86c4a294a27b.png">

Thank you for the quick fix!

**Comment by wustho** [comment]
Glad to help. But it wont, do much good with code block or quote, since it is initilly written for use in any terminal, which means some of them wont have italic features or mixed fonts.

Closing the issue...
